#ifndef Corburt_Database_h_Include_Guard
#define Corburt_Database_h_Include_Guard
#include "cbbase.h"
itemdb itemdbs[]={
    {.id=1,.name=L"Wooden Stick",
        .type=db_itemtype_weapon,
        .price=5,
        .cd=45,
        .desc=L"\"Now let's do it with a wooden stick!\"",
        .stats={.min_=1,.max_=3,.acc=-5}
    },
    {.id=2,.name=L"Rusty Knife",
        .type=db_itemtype_weapon,
        .price=5,
        .cd=30,
        .desc=L"A simple rusty knife. What do you expect?",
        .stats={.min_=1,.max_=3,.acc=3}
    },
    {.id=3,.name=L"Stiletto",
        .type=db_itemtype_weapon,
        .price=25,
        .cd=42,
        .desc=L"Born for stabbing.",
        .stats={.min_=1,.max_=5,.acc=5}
    },
    {.id=4,.name=L"Iron Shortsword",
        .type=db_itemtype_weapon,
        .price=60,
        .cd=56,
        .desc=L"Classic newbie weapon.",
        .stats={.min_=4,.max_=6,.acc=3}
    },
    {.id=5,.name=L"Vicious Stiletto",
        .type=db_itemtype_weapon,
        .price=100,
        .cd=24,
        .crit=500,
        .desc=L"Specially enhanced for your stabbing pleasure...",
        .stats={.min_=2,.max_=9,.acc=13}
    },
    {.id=6,.name=L"Knife",
        .type=db_itemtype_weapon,
        .price=28,
        .cd=42,
        .desc=L"Designed to cut things, not people.",
        .stats={.min_=2,.max_=5,.acc=4}
    },
    {.id=7,.name=L"Rusty Sword",
        .type=db_itemtype_weapon,
        .price=80,
        .cd=32,
        .crit=500,
        .desc=L"Occasionally reveals its power.",
        .stats={.min_=3,.max_=7}
    },
    {.id=8,.name=L"Tiny Green Leaf",
        .type=db_itemtype_consume,
        .price=1,
        .desc=L"Sprout of some exotic plant.",
        .stats={.min_=1,.max_=2}
    },
    {.id=9,.name=L"Small Green Leaf",
        .type=db_itemtype_consume,
        .price=3,
        .desc=L"Young leaves of some exotic plant.",
        .stats={.min_=2,.max_=4}
    },
    {.id=10,.name=L"Immature Green Leaf",
        .type=db_itemtype_consume,
        .price=8,
        .desc=L"Immature leaves of some exotic plant.",
        .stats={.min_=5,.max_=12}
    },
    {.id=11,.name=L"Green Leaf",
        .type=db_itemtype_consume,
        .price=13,
        .desc=L"Leaves of some exotic plant.",
        .stats={.min_=13,.max_=20}
    },
    {.id=12,.name=L"Large Green Leaf",
        .type=db_itemtype_consume,
        .price=21,
        .desc=L"Larger leaves of some exotic plant.",
        .stats={.min_=15,.max_=35}
    },
    {.id=13,.name=L"Huge Green Leaf",
        .type=db_itemtype_consume,
        .price=53,
        .desc=L"Huge leaves of some exotic plant.",
        .stats={.min_=30,.max_=55}
    },
    {.id=14,.name=L"Enormous Green Leaf",
        .type=db_itemtype_consume,
        .price=96,
        .desc=L"Enormous leaves of some exotic plant.",
        .stats={.min_=65,.max_=115}
    },
    {.id=15,.name=L"Tremendous Green Leaf",
        .type=db_itemtype_consume,
        .price=134,
        .desc=L"Tremendous leaves of some exotic plant.",
        .stats={.min_=175,.max_=255}
    },
    {.id=16,.name=L"Thin Cloth Armor",
        .type=db_itemtype_armor,
        .price=20,
        .desc=L"Basically, it's plain clothes.",
        .stats={.dod=8,.acc=5}
    },
    {.id=17,.name=L"Leather Armor",
        .type=db_itemtype_armor,
        .price=40,
        .desc=L"Pig skin, stronger than most people's.",
        .stats={.def=2,.dod=4,.acc=5}
    },
    {.id=18,.name=L"Chain Shirt",
        .type=db_itemtype_armor,
        .price=75,
        .desc=L"Do you feel chained?",
        .stats={.def=5,.dod=2,.acc=9}
    },
    {.id=19,.name=L"Hide",
        .type=db_itemtype_armor,
        .price=35,
        .desc=L"Pig skin, stronger than most pigs'.",
        .stats={.def=4,.acc=2}
    },
    {.id=20,.name=L"Scalemail Armor",
        .type=db_itemtype_armor,
        .price=85,
        .desc=L"They're like flappy wings!",
        .stats={.def=7,.dod=-1,.acc=5}
    },
    {.id=21,.name=L"Chainmail Armor",
        .type=db_itemtype_armor,
        .price=185,
        .desc=L"\"The more you tank\"",
        .stats={.def=10,.dod=-3,.acc=8}
    },
    {.id=22,.name=L"Breastplate Armor",
        .type=db_itemtype_armor,
        .price=290,
        .desc=L"\"The less you dodge\"",
        .stats={.def=12,.dod=-4,.acc=11}
    },
    {.id=23,.name=L"Platemail Armor",
        .type=db_itemtype_armor,
        .price=400,
        .desc=L"Only the weak dodges.",
        .stats={.def=15,.dod=-7,.acc=15}
    },
    {.id=24,.name=L"Full Platemail Armor",
        .type=db_itemtype_armor,
        .price=650,
        .desc=L"Dodging? What's that?",
        .stats={.def=20,.dod=-10,.acc=23}
    },
    {.id=25,.name=L"Necklace of Slight Regeneration",
        .type=db_itemtype_accessory,
        .price=75,
        .desc=L"It's... Blue?",
        .stats={.regen=1}
    },
    {.id=26,.name=L"Minor Healing Potion",
        .type=db_itemtype_consume,
        .price=15,
        .desc=L"The unique precision of chemical reagents.",
        .stats={.min_=20,.max_=20}
    },
    {.id=27,.name=L"Small Healing Potion",
        .type=db_itemtype_consume,
        .price=35,
        .desc=L"The unique precision of chemical reagents.",
        .stats={.min_=40,.max_=40}
    },
    {.id=28,.name=L"Necklace of Mild Regeneration",
        .type=db_itemtype_accessory,
        .price=405,
        .desc=L"Why aren't necklaces of regeneration red?",
        .stats={.regen=3,.def=1,.dod=3}
    },
    {.id=29,.name=L"Paper",
        .type=db_itemtype_weapon,
        .price=2,
        .cd=8,
        .desc=L"For the long-forgotten glory...",
        .stats={.min_=0,.max_=1,.def=-1,.acc=1}
    },
    {.id=30,.name=L"Fan",
        .type=db_itemtype_weapon,
        .price=5,
        .cd=90,
        .desc=L"Impractical.",
        .stats={.min_=-1,.max_=0}
    },
    {.id=31,.name=L"Toilet Paper",
        .type=db_itemtype_misc,
        .price=1,
        .desc=L"Might be brand new. Might not...",
    },
    {.id=32,.name=L"Scissors",
        .type=db_itemtype_weapon,
        .price=7,
        .cd=24,
        .desc=L"Two pieces of blade, but half the damage.",
        .stats={.min_=1,.max_=2}
    },
    {.id=33,.name=L"Wooden Block",
        .type=db_itemtype_misc,
        .price=4,
        .desc=L"Why would you keep it?"
    },
    {.id=34,.name=L"Apple",
        .type=db_itemtype_consume,
        .price=2,
        .desc=L"\"Apfel, Nuss und Mandelkern,\"",
        .stats={.min_=2,.max_=2}
    },
    {.id=35,.name=L"Banana",
        .type=db_itemtype_consume,
        .price=2,
        .desc=L"Have a bana-na.",
        .stats={.min_=2,.max_=2}
    },
    {.id=36,.name=L"Meat",
        .type=db_itemtype_consume,
        .price=10,
        .desc=L"It's impossible to figure out what kind of meat this is.",
        .stats={.min_=10,.max_=12}
    },
    {.id=37,.name=L"Fried Salmon",
        .type=db_itemtype_consume,
        .price=25,
        .desc=L"\"Why wouldn't you like to have a fish?\"\n"
                "    -- fishstore",
        .stats={.min_=3,.max_=9}
    },
    {.id=38,.name=L"Broken Bone Longsword",
        .type=db_itemtype_weapon,
        .price=2650,
        .cd=120,
        .crit=343,
        .desc=L"Are they getting the material from themselves? Well...",
        .stats={.min_=22,.max_=35,.acc=30,.dod=14,.con=4}
    },
    {.id=39,.name=L"Fang",
        .type=db_itemtype_weapon,
        .price=35,
        .cd=28,
        .desc=L"It's really hard to cut things with it.",
        .stats={.min_=2,.max_=5,.acc=10}
    },
    {.id=40,.name=L"Broadsword",
        .type=db_itemtype_weapon,
        .price=250,
        .cd=90,
        .desc=L"Your optimal choice for close combat.",
        .stats={.min_=12,.max_=16}
    },
};
enemydb enemydbs[]={
    {.id=1,.name=L"Vagrant",
        .type=db_enemytype_plain,
//        .desc=L"They have no homes. Just like you...",
        .exp=12,
        .loot={.moneymin=0,.moneymax=2,.weapon=2},
        .stats={.hpmax=8,.atk=1,.def=0,.acc=15,.dod=-25,.con=1}
    },
    {.id=2,.name=L"Thug",
        .type=db_enemytype_plain,
//        .desc=L"Avocation: killing cute animals.",
        .exp=20,
        .loot={.moneymin=0,.moneymax=4,.weapon=6},
        .stats={.hpmax=15,.atk=3,.def=1,.acc=12,.dod=-15,.con=1}
    },
    {.id=3,.name=L"Gang Member",
        .type=db_enemytype_plain,
//        .desc=L"Yo, come on and be a gangster!",
        .exp=80,
        .loot={.moneymin=2,.moneymax=9,.weapon=3,.armor=16},
        .stats={.hpmax=40,.atk=12,.def=12,.acc=27,.dod=-9,.con=3}
    },
    {.id=4,.name=L"Gang Leader",
        .type=db_enemytype_plain,
//        .desc=L"Do you wanna be a gang-star?",
        .exp=135,
        .loot={.moneymin=16,.moneymax=35,.weapon=4,.armor=17},
        .stats={.hpmax=62,.atk=17,.def=25,.acc=45,.dod=8,.con=5}
    },
    {.id=5,.name=L"Robber",
        .type=db_enemytype_plain,
//        .desc=L"\"Show me what you've got...\"",
        .exp=110,
        .loot={.moneymin=3,.moneymax=18,.weapon=5,.armor=16},
        .stats={.hpmax=50,.atk=17,.def=8,.acc=47,.dod=65,.con=4}
    },
    {.id=6,.name=L"Skeleton",
        .type=db_enemytype_plain,
//        .desc=L"Do not disturb the peace of the dead... Well... Too late...",
        .exp=3580,
        .loot={.moneymin=53,.moneymax=78,.weapon=38},
        .stats={.hpmax=489,.atk=63,.def=45,.acc=156,.dod=97,.con=39}
    },
    {.id=7,.name=L"Bird",
        .type=db_enemytype_plain,
//        .desc=L"Let's just call it \"a bird\".",
        .exp=1,
        .loot={.moneymin=0,.moneymax=1},
        .stats={.hpmax=1,.atk=1,.def=0,.acc=35,.dod=25,.con=0}
    },
    {.id=8,.name=L"Ant",
        .type=db_enemytype_plain,
        .exp=1,
        .loot={.moneymin=0,.moneymax=0},
        .stats={.hpmax=2,.atk=1,.def=0,.acc=1,.dod=55,.con=1}
    },
    {.id=9,.name=L"Sheep",
        .type=db_enemytype_plain,
        .exp=1,
        .loot={.moneymin=0,.moneymax=0,.drops[0]={36,1000}},
        .stats={.hpmax=25,.atk=1,.def=0,.acc=10,.dod=-50,.con=1}
    },
    {.id=10,.name=L"Cow",
        .type=db_enemytype_plain,
        .exp=1,
        .loot={.moneymin=0,.moneymax=0,.drops[0]={36,1000}},
        .stats={.hpmax=35,.atk=1,.def=0,.acc=10,.dod=-70,.con=1}
    },
    {.id=11,.name=L"Grasshopper",
        .type=db_enemytype_plain,
        .exp=3,
        .loot={.moneymin=0,.moneymax=0},
        .stats={.hpmax=1,.atk=2,.def=0,.acc=5,.dod=120,.con=1}
    },
    {.id=12,.name=L"Mantis",
        .type=db_enemytype_plain,
        .exp=5,
        .loot={.moneymin=0,.moneymax=0},
        .stats={.hpmax=1,.atk=5,.def=1,.acc=80,.dod=20,.con=1}
    },
    {.id=13,.name=L"Furious Squirrel",
        .type=db_enemytype_plain,
        .exp=15,
        .loot={.moneymin=0,.moneymax=2},
        .stats={.hpmax=8,.atk=2,.def=0,.acc=45,.dod=25,.con=1}
    },
    {.id=14,.name=L"Deer",
        .type=db_enemytype_plain,
        .exp=30,
        .loot={.moneymin=0,.moneymax=0,.drops[0]={36,1000}},
        .stats={.hpmax=40,.atk=5,.def=6,.acc=34,.dod=40,.con=3}
    },
    {.id=15,.name=L"Wolf",
        .type=db_enemytype_plain,
        .exp=75,
        .loot={.moneymin=0,.moneymax=5,.weapon=39},
        .stats={.hpmax=60,.atk=12,.def=8,.acc=34,.dod=70,.con=4}
    },
    {.id=16,.name=L"Bandit",
        .type=db_enemytype_plain,
        .exp=120,
        .loot={.moneymin=5,.moneymax=40,.weapon=3,.armor=20},
        .stats={.hpmax=40,.atk=12,.def=12,.acc=27,.dod=-9,.con=3}
    }
};
roomdb roomdbs[]={
    {.id=1,
        .x=0,
        .y=0,
        .region=db_roomregion_nlcity,
        .name=L"Town Square of the Nameless City",
        .desc=L"You have come to the town square of a nameless city. It lies in the center of the city.",
        .type=db_roomtype_birth,
        .exits={[dir_East]=19,[dir_West]=5,[dir_North]=2,[dir_South]=13},
    },
    {.id=2,
        .x=0,
        .y=-1,
        .region=db_roomregion_nlcity,
        .name=L"Street",
        .desc=L"This ordinary street runs south and north, passing through the center of the city. There are few pedestrians on the street.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=23,[dir_West]=3,[dir_North]=10,[dir_South]=1},
    },
    {.id=3,
        .x=-1,
        .y=-1,
        .region=db_roomregion_nlcity,
        .name=L"Alley",
        .desc=L"The Alley leads to the park in the city. The reason the park was built had disappeared along with the city's name.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=2,[dir_West]=4},
    },
    {.id=4,
        .x=-2,
        .y=-1,
        .region=db_roomregion_nlcity,
        .name=L"Park Entrance",
        .desc=L"You stand at the entrance of the park. Stone statues of two guards stand on either side of the entrance.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=3,[dir_West]=9,[dir_North]=7,[dir_South]=6},
    },
    {.id=5,
        .x=-1,
        .y=0,
        .region=db_roomregion_nlcity,
        .name=L"Street",
        .desc=L"You see old houses on both sides of the street, some are inhabited.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=1,[dir_West]=6,[dir_South]=20},
        .table={1},
    },
    {.id=6,
        .x=-2,
        .y=0,
        .region=db_roomregion_nlcity,
        .name=L"Street",
        .desc=L"Houses around seems to get older and older.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=5,[dir_West]=49,[dir_North]=4,[dir_South]=16},
        .table={1,2},
    },
    {.id=7,
        .x=-2,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Park",
        .desc=L"The weeds are growing tall and apparently not managed well, among which exotic plants are sparsely visible. The roads are lined with wooden guardrails, apparently made of precious wood.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=8,[dir_North]=51,[dir_South]=4},
    },
    {.id=8,
        .x=-3,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Park",
        .desc=L"You see woods with transparent amber leaves, trees with leaves that look like pure gold, shrub with crimson vines that bleed, herbs with blooming fantastic flowers that flickers, et cetera.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=7,[dir_South]=9},
    },
    {.id=9,
        .x=-3,
        .y=-1,
        .region=db_roomregion_nlcity,
        .name=L"Park Shop",
        .desc=L"A shop can be seen among the lush vegetation.",
        .type=db_roomtype_store,
        .exits={[dir_East]=4,[dir_North]=8},
        .table={8,9,10,11,12,13,14,15},
    },
    {.id=10,
        .x=0,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Street",
        .desc=L"There are two stores on the sides of this part of the street, great for novice adventurers.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=22,[dir_West]=21,[dir_North]=11,[dir_South]=2},
    },
    {.id=11,
        .x=0,
        .y=-3,
        .region=db_roomregion_nlcity,
        .name=L"Street",
        .desc=L"The street goes further north.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=42,[dir_West]=50,[dir_North]=12,[dir_South]=10},
    },
    {.id=12,
        .x=0,
        .y=-4,
        .region=db_roomregion_nlcity,
        .name=L"City Entrance",
        .desc=L"You have arrived at the entrance of this small city. The city does not have a name, but it can also be said that its name is exactly \"the Nameless City\".\nNo one guards this entrance. A row of stone statues of soldiers stand here, and they look as if they were still alive.",
        .type=db_roomtype_gate,
        .exits={[dir_North]=53,[dir_South]=11},
    },
    {.id=13,
        .x=0,
        .y=1,
        .region=db_roomregion_nlcity,
        .name=L"Street",
        .desc=L"There is a not-so-thick layer of dust on the floor of the street. The wind picks up dust when it blows.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=36,[dir_West]=20,[dir_North]=1,[dir_South]=14},
    },
    {.id=14,
        .x=0,
        .y=2,
        .region=db_roomregion_nlcity,
        .name=L"Street Intersection",
        .desc=L"This is a small intersection. The road to the west seems to lead to a dark path.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=37,[dir_West]=18,[dir_North]=13,[dir_South]=15},
    },
    {.id=15,
        .x=0,
        .y=3,
        .region=db_roomregion_nlcity,
        .name=L"City Gate",
        .desc=L"You are at the southern gate of the city. A group of stone soldiers salute to the south.",
        .type=db_roomtype_gate,
        .exits={[dir_North]=14},
    },
    {.id=16,
        .x=-2,
        .y=1,
        .region=db_roomregion_nlcity,
        .name=L"Street",
        .desc=L"It looks a little dark.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=20,[dir_North]=6,[dir_South]=17},
    },
    {.id=17,
        .x=-2,
        .y=2,
        .region=db_roomregion_nlcity,
        .name=L"Darker Path",
        .desc=L"This path is very dark, definitely not the safest place to go.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=18,[dir_West]=47,[dir_North]=16},
        .table={2},
    },
    {.id=18,
        .x=-1,
        .y=2,
        .region=db_roomregion_nlcity,
        .name=L"Dark Path",
        .desc=L"The path is dark. The low eaves of the houses block light that comes in.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=14,[dir_West]=17,[dir_North]=20,[dir_South]=45},
        .table={1,2},
    },
    {.id=19,
        .x=1,
        .y=0,
        .region=db_roomregion_nlcity,
        .name=L"Training Grounds",
        .desc=L"An elderly swordsman stood in the room practicing his myriad arts techniques. He looks more like a machine or a golem than a human.",
        .type=db_roomtype_train,
        .exits={[dir_West]=1},
    },
    {.id=20,
        .x=-1,
        .y=1,
        .region=db_roomregion_nlcity,
        .name=L"Residential Area",
        .desc=L"You walk through the residential area in the city. There are not many residents here, and two thirds of the houses are empty.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=13,[dir_West]=16,[dir_North]=5,[dir_South]=18},
    },
    {.id=21,
        .x=-1,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Adventurer's Shop",
        .desc=L"A man sits at the counter. He has a large scar on his face.",
        .type=db_roomtype_store,
        .exits={[dir_East]=10},
        .table={2,3,6,4,7,5,16,17,18,19,20,21,22,23,24},
    },
    {.id=22,
        .x=1,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Mad Alchemist's Shop",
        .desc=L"The mad alchemist stares at you. In his hand he holds a bottle of potion that kept changing colors. Looks toxic.",
        .type=db_roomtype_store,
        .exits={[dir_East]=24,[dir_West]=10,[dir_South]=23},
        .table={26,27,25,28},
    },
    {.id=23,
        .x=1,
        .y=-1,
        .region=db_roomregion_nlcity,
        .name=L"Market",
        .desc=L"Various cheap items are available in the market.",
        .type=db_roomtype_store,
        .exits={[dir_East]=25,[dir_West]=2,[dir_North]=22},
        .table={31,29,33,30,32,6,34,35,36,37},
    },
    {.id=24,
        .x=2,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Side Street Junction",
        .desc=L"The side street ends here. You can see a path to the east.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=26,[dir_West]=22,[dir_South]=25},
    },
    {.id=25,
        .x=2,
        .y=-1,
        .region=db_roomregion_nlcity,
        .name=L"Side Street",
        .desc=L"The side street runs parallel to main street, which connects the entrance and the southern gate of the city.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=23,[dir_North]=24,[dir_South]=32},
    },
    {.id=26,
        .x=3,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Path",
        .desc=L"To the east is the cemetery.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=27,[dir_West]=24,[dir_North]=44},
    },
    {.id=27,
        .x=4,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Cemetery Path",
        .desc=L"You stand at the end of the narrow path that leads to the cemetery. The cemetery is on low ground and you can see most of the cemetery from this location. Yet the eastern part of the cemetery is shrouded in darkness.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=28,[dir_West]=26,[dir_North]=65},
    },
    {.id=28,
        .x=5,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Cemetery",
        .desc=L"There are tombstones all around. Apparently, the number of tombstones is far greater than the number of inhabitants of the town.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=31,[dir_West]=27,[dir_South]=29},
    },
    {.id=29,
        .x=5,
        .y=-1,
        .region=db_roomregion_nlcity,
        .name=L"Cemetery",
        .desc=L"Tombstones are crowded.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=30,[dir_North]=28},
    },
    {.id=30,
        .x=6,
        .y=-1,
        .region=db_roomregion_nlcity,
        .name=L"Cemetery",
        .desc=L"Do not disturb the peace of the dead.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=29,[dir_North]=31},
        .table={6},
    },
    {.id=31,
        .x=6,
        .y=-2,
        .region=db_roomregion_nlcity,
        .name=L"Cemetery",
        .desc=L"Is it because the city was once too prosperous, or because it is too decadent now? Or is it neither, just because the history here is too old?",
        .type=db_roomtype_plain,
        .exits={[dir_West]=28,[dir_South]=30},
        .table={6},
    },
    {.id=32,
        .x=2,
        .y=0,
        .region=db_roomregion_nlcity,
        .name=L"Side Street",
        .desc=L"This is another T-junction on the side street.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=33,[dir_North]=25,[dir_South]=35},
    },
    {.id=33,
        .x=3,
        .y=0,
        .region=db_roomregion_nlcity,
        .name=L"Alley",
        .desc=L"It's not very clean and there is some unknown garbage on the ground.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=32,[dir_South]=34},
    },
    {.id=34,
        .x=3,
        .y=1,
        .region=db_roomregion_nlcity,
        .name=L"Alley Dead End",
        .desc=L"Cascading houses prevent you from going further south.",
        .type=db_roomtype_plain,
        .exits={[dir_North]=33},
    },
    {.id=35,
        .x=2,
        .y=1,
        .region=db_roomregion_nlcity,
        .name=L"Side Street Curve",
        .desc=L"Some robbers like to crouch at the bend of the road to rob.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=36,[dir_North]=32},
        .table={5},
    },
    {.id=36,
        .x=1,
        .y=1,
        .region=db_roomregion_nlcity,
        .name=L"Side Street Curve",
        .desc=L"How is the law and order maintained here? No one is patrolling the streets at all.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=35,[dir_West]=13,[dir_South]=37},
    },
    {.id=37,
        .x=1,
        .y=2,
        .region=db_roomregion_nlcity,
        .name=L"Side Street",
        .desc=L"Here the side street merges with the main road, leading to the gate to the south.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=14,[dir_North]=36,[dir_South]=38},
    },
    {.id=38,
        .x=1,
        .y=3,
        .region=db_roomregion_nlcity,
        .name=L"Artificial lake",
        .desc=L"It can be seen that this lake used to be a standard circle.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=39,[dir_North]=37,[dir_South]=41},
    },
    {.id=39,
        .x=2,
        .y=3,
        .region=db_roomregion_nlcity,
        .name=L"Artificial lake",
        .desc=L"There are many fish in the lake. Obviously, each of them is very valuable.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=38,[dir_South]=40},
    },
    {.id=40,
        .x=2,
        .y=4,
        .region=db_roomregion_nlcity,
        .name=L"Artificial lake",
        .desc=L"The water is relatively clear and you can see the deep bottom of the lake. What have kept the water clear here?",
        .type=db_roomtype_plain,
        .exits={[dir_West]=41,[dir_North]=39},
    },
    {.id=41,
        .x=1,
        .y=4,
        .region=db_roomregion_nlcity,
        .name=L"Artificial lake",
        .desc=L"Some wooden boats are moored here. They are badly decayed and overgrown with shellfish and algae.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=40,[dir_North]=38},
    },
    {.id=42,
        .x=1,
        .y=-3,
        .region=db_roomregion_nlcity,
        .name=L"Road",
        .desc=L"It feels strange that there are not many pedestrians on such a wide road.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=43,[dir_West]=11},
    },
    {.id=43,
        .x=2,
        .y=-3,
        .region=db_roomregion_nlcity,
        .name=L"Road",
        .desc=L"Such a wide road might have been prepared for a huge carriage parade.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=44,[dir_West]=42},
    },
    {.id=44,
        .x=3,
        .y=-3,
        .region=db_roomregion_nlcity,
        .name=L"Road",
        .desc=L"The road came to an abrupt end.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=43,[dir_South]=26},
    },
    {.id=45,
        .x=-1,
        .y=3,
        .region=db_roomregion_nlcity,
        .name=L"Gangsters' Corner",
        .desc=L"Gang members frequent this corner.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=46,[dir_North]=18},
        .table={3},
    },
    {.id=46,
        .x=-2,
        .y=3,
        .region=db_roomregion_nlcity,
        .name=L"Gang Base",
        .desc=L"All the gang members give hostile glances.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=45},
        .table={4,3,3,3},
    },
    {.id=47,
        .x=-3,
        .y=2,
        .region=db_roomregion_nlcity,
        .name=L"Yet Darker Path",
        .desc=L"It is still dark here. This is probably the darkest spot on the path. No one came at all, maybe the darkness scared the gangs away.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=17,[dir_North]=48},
    },
    {.id=48,
        .x=-3,
        .y=1,
        .region=db_roomregion_nlcity,
        .name=L"Darker Path",
        .desc=L"The path is too dark.",
        .type=db_roomtype_plain,
        .exits={[dir_North]=49,[dir_South]=47},
    },
    {.id=49,
        .x=-3,
        .y=0,
        .region=db_roomregion_nlcity,
        .name=L"Dark Path",
        .desc=L"Are the streets of this city without street lights?",
        .type=db_roomtype_plain,
        .exits={[dir_East]=6,[dir_South]=48},
    },
    {.id=50,
        .x=-1,
        .y=-3,
        .region=db_roomregion_nlcity,
        .name=L"Road",
        .desc=L"Even large armies can easily travel on this wide road.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=11,[dir_West]=51},
    },
    {.id=51,
        .x=-2,
        .y=-3,
        .region=db_roomregion_nlcity,
        .name=L"Road",
        .desc=L"The wind blew in from the west gate and blew across the road.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=50,[dir_West]=52,[dir_South]=7},
    },
    {.id=52,
        .x=-3,
        .y=-3,
        .region=db_roomregion_nlcity,
        .name=L"City Gate",
        .desc=L"There are many more stone statues here than at the northern gate. ",
        .type=db_roomtype_gate,
        .exits={[dir_East]=51,[dir_West]=93},
    },
    {.id=53,
        .x=0,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Forest Path",
        .desc=L"Paths weave through the forest, among which the widest one runs north.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=60,[dir_West]=54,[dir_North]=58,[dir_South]=12},
    },
    {.id=54,
        .x=-1,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Forest Path",
        .desc=L"There are birds chirping in trees.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=53,[dir_South]=55},
        .table={7},
    },
    {.id=55,
        .x=-1,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Forest Path",
        .desc=L"The path goes along the city walls.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=56,[dir_North]=54},
    },
    {.id=56,
        .x=-2,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Path to the Craters",
        .desc=L"The path is twisted and leads to the craters.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=55,[dir_North]=57},
        .table={7},
    },
    {.id=57,
        .x=-2,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Path to the Craters",
        .desc=L"There is smoke in the air.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=90,[dir_South]=56},
    },
    {.id=58,
        .x=0,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Forest Path",
        .desc=L"There are some broken walls on the road. You go through them and you see the old gate to the west.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=72,[dir_West]=87,[dir_North]=59,[dir_South]=53},
        .table={13},
    },
    {.id=59,
        .x=0,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Forest Path",
        .desc=L"The path goes further north.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=73,[dir_West]=84,[dir_North]=86,[dir_South]=58},
    },
    {.id=60,
        .x=1,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"This looks like an entrance to something.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=71,[dir_West]=53,[dir_North]=72,[dir_South]=61},
    },
    {.id=61,
        .x=1,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"A few planks of wood peeped out from between the bricks and stones. Looks like some cracked furniture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=62,[dir_North]=60},
        .table={8},
    },
    {.id=62,
        .x=2,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"There is nothing much to see here.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=63,[dir_West]=61},
        .table={8,8},
    },
    {.id=63,
        .x=3,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"To the north there is flat ground.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=62,[dir_North]=68},
    },
    {.id=64,
        .x=4,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Forest Trail",
        .desc=L"The trail might have once been a wide road. Who knows?",
        .type=db_roomtype_plain,
        .exits={[dir_North]=67,[dir_South]=65},
        .table={7},
    },
    {.id=65,
        .x=4,
        .y=-3,
        .region=db_roomregion_forest,
        .name=L"Forest Trail",
        .desc=L"There is a small hut on one side of the trail.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=66,[dir_North]=64,[dir_South]=27},
    },
    {.id=66,
        .x=5,
        .y=-3,
        .region=db_roomregion_forest,
        .name=L"Cemetary Hut",
        .desc=L"The hut is piled with used shovels. All the shovels were rusty, stained with mud and blackened blood.\nNo one lives here.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=65},
    },
    {.id=67,
        .x=4,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"This might be the backdoor of the destructed building.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=68,[dir_South]=64},
    },
    {.id=68,
        .x=3,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Flat ground",
        .desc=L"This must have once been the heart of the building.\nAn area of flat ground has been cleared from the ruins. A man sits on a large rock in the middle of the flat ground and looks at the ruins around him. He wears an indigo robe.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=67,[dir_West]=71,[dir_North]=69,[dir_South]=63},
    },
    {.id=69,
        .x=3,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"A solitary door stands here. There is nothing behind.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=156,[dir_West]=70,[dir_North]=75,[dir_South]=68},
    },
    {.id=70,
        .x=2,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"Apparently, a very large building was built here.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=69,[dir_West]=72,[dir_North]=74},
    },
    {.id=71,
        .x=2,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"This might be some passage leading to the heart of the building.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=68,[dir_West]=60},
    },
    {.id=72,
        .x=1,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"The debris may have become a home to some insects.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=70,[dir_West]=58,[dir_North]=73,[dir_South]=60},
        .table={8,8,8,8,8,8,8,8,8},
    },
    {.id=73,
        .x=1,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Wall Collapse",
        .desc=L"More walls had collapsed here.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=74,[dir_West]=59,[dir_South]=72},
    },
    {.id=74,
        .x=2,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Foot of the Hill",
        .desc=L"You can go up the hill from here.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=75,[dir_West]=73,[dir_South]=70},
    },
    {.id=75,
        .x=3,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Debris",
        .desc=L"This looks like a cloister. There are broken statues everywhere, and shards of glass or crystal scatter on the ground.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=74,[dir_South]=69},
    },
    {.id=76,
        .x=2,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=154,[dir_West]=77},
    },
    {.id=77,
        .x=1,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=76,[dir_North]=78},
    },
    {.id=78,
        .x=1,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=79,[dir_North]=145,[dir_South]=77},
    },
    {.id=79,
        .x=0,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=78},
    },
    {.id=80,
        .x=-1,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Foot of the Hill",
        .desc=L"You can go up the hill from here. It's not really a tall hill.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=81},
        .table={14},
    },
    {.id=81,
        .x=-2,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"The trees are sleeping.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=80,[dir_South]=82},
    },
    {.id=82,
        .x=-2,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"The foliage begins to dim the light slightly.",
        .type=db_roomtype_plain,
        .exits={[dir_North]=81,[dir_South]=83},
        .table={13},
    },
    {.id=83,
        .x=-2,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"The forest path ends here. From here, there is no more sign of a single human being.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=84,[dir_North]=82},
    },
    {.id=84,
        .x=-1,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Forest Path",
        .desc=L"You are still on the forest paths.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=59,[dir_West]=83,[dir_North]=85,[dir_South]=87},
    },
    {.id=85,
        .x=-1,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Another Dead End",
        .desc=L"This is another dead end on the forest path.",
        .type=db_roomtype_plain,
        .exits={[dir_South]=84},
        .table={8,8},
    },
    {.id=86,
        .x=0,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Forest Path Dead End",
        .desc=L"You have come to the end of the forest path. You can see hills to the north, but the thick forest blocks your way.",
        .type=db_roomtype_plain,
        .exits={[dir_South]=59},
    },
    {.id=87,
        .x=-1,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"City Gate Collapse",
        .desc=L"You can see what was once the gate of the city. Several broken stone columns stand on the ground with what seems to be some writing carved on them, but you could not make out anything.\nIn front of the gate is a statue broken in half. It is a dozen meters high, with a golden glow flowing from the top. The inscription on the base of the statue reads: \"Forever live the great kings.\"\nThe severed upper part of the statue is not seen anywhere. They may have been broken into little pieces and buried in rocks.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=58,[dir_West]=88,[dir_North]=84},
    },
    {.id=88,
        .x=-2,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Broken Walls",
        .desc=L"High walls fell down here.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=87,[dir_West]=89},
    },
    {.id=89,
        .x=-3,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Trees",
        .desc=L"Trees sprouted from the ruins. They look unhealthy.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=88,[dir_West]=114,[dir_South]=90},
        .table={13,13},
    },
    {.id=90,
        .x=-3,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Wreckage",
        .desc=L"This is the wreckage of some unknown construction.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=57,[dir_West]=113,[dir_North]=89,[dir_South]=91},
    },
    {.id=91,
        .x=-3,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=92,[dir_North]=90},
    },
    {.id=92,
        .x=-4,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=91,[dir_West]=100,[dir_North]=113,[dir_South]=93},
    },
    {.id=93,
        .x=-4,
        .y=-3,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater. There is a hole on your west.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=52,[dir_West]=99,[dir_North]=92,[dir_South]=94},
    },
    {.id=94,
        .x=-4,
        .y=-2,
        .region=db_roomregion_forest,
        .name=L"Crater",
        .desc=L"You are in a crater.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=98,[dir_North]=93,[dir_South]=95},
    },
    {.id=95,
        .x=-4,
        .y=-1,
        .region=db_roomregion_forest,
        .name=L"Wreckage",
        .desc=L"The collapsed buildings piled up a mountain of stone on the ground.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=96,[dir_North]=94,[dir_South]=157},
    },
    {.id=96,
        .x=-5,
        .y=-1,
        .region=db_roomregion_forest,
        .name=L"Short Trees",
        .desc=L"The trees are short.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=95,[dir_North]=98,[dir_South]=97},
        .table={14},
    },
    {.id=97,
        .x=-5,
        .y=0,
        .region=db_roomregion_forest,
        .name=L"Shrubs",
        .desc=L"The air begins to get wet and salty.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=160,[dir_North]=96},
        .table={11},
    },
    {.id=98,
        .x=-5,
        .y=-2,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater. The hole is to the north of you.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=94,[dir_West]=158,[dir_North]=99,[dir_South]=96},
    },
    {.id=99,
        .x=-5,
        .y=-3,
        .region=db_roomregion_forest,
        .name=L"Hole",
        .desc=L"There is a huge hole in the ground. There is a faint reddish-purple glow in it, and it is possible that something is still burning below.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=93,[dir_West]=107,[dir_North]=100,[dir_South]=98},
    },
    {.id=100,
        .x=-5,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater, and to the south you can see the big hole.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=92,[dir_West]=106,[dir_North]=101,[dir_South]=99},
    },
    {.id=101,
        .x=-5,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=103,[dir_North]=102,[dir_South]=100},
    },
    {.id=102,
        .x=-5,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Pile of Bricks",
        .desc=L"There is a lot of dust on the ground.",
        .type=db_roomtype_plain,
        .exits={[dir_South]=101},
    },
    {.id=103,
        .x=-6,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=101,[dir_West]=104,[dir_South]=106},
    },
    {.id=104,
        .x=-7,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Wreckage",
        .desc=L"\"Nothing again nothing.\"",
        .type=db_roomtype_plain,
        .exits={[dir_East]=103,[dir_South]=105},
    },
    {.id=105,
        .x=-7,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Wreckage",
        .desc=L"This is the wreckage of some unknown destruction.",
        .type=db_roomtype_plain,
        .exits={[dir_North]=104,[dir_South]=159},
    },
    {.id=106,
        .x=-6,
        .y=-4,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=100,[dir_North]=103,[dir_South]=107},
    },
    {.id=107,
        .x=-6,
        .y=-3,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater, around a gigantic hole.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=99,[dir_West]=159,[dir_North]=106,[dir_South]=158},
    },
    {.id=108,
        .x=-6,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_North]=109},
        .table={10,10,9,9},
    },
    {.id=109,
        .x=-6,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=110,[dir_West]=189,[dir_North]=129,[dir_South]=108},
        .table={10,9},
    },
    {.id=110,
        .x=-5,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=115,[dir_West]=109,[dir_North]=111},
        .table={9},
    },
    {.id=111,
        .x=-5,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=112,[dir_West]=129,[dir_North]=128,[dir_South]=110},
        .table={10},
    },
    {.id=112,
        .x=-4,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=117,[dir_West]=111,[dir_North]=119,[dir_South]=115},
        .table={9},
    },
    {.id=113,
        .x=-4,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"You can see the crater to the south.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=90,[dir_North]=114,[dir_South]=92},
        .table={7},
    },
    {.id=114,
        .x=-4,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"The forest is infested with angry animals.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=89,[dir_South]=113},
        .table={13,13,13,13,13},
    },
    {.id=115,
        .x=-4,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=116,[dir_West]=110,[dir_North]=112},
        .table={9,10},
    },
    {.id=116,
        .x=-3,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=115,[dir_North]=117},
        .table={10},
    },
    {.id=117,
        .x=-3,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=112,[dir_North]=118,[dir_South]=116},
        .table={10,10,9},
    },
    {.id=118,
        .x=-3,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=119,[dir_South]=117},
        .table={10},
    },
    {.id=119,
        .x=-4,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=118,[dir_West]=128,[dir_South]=112},
        .table={9},
    },
    {.id=120,
        .x=-2,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=121},
    },
    {.id=121,
        .x=-3,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=120,[dir_West]=122,[dir_North]=131},
    },
    {.id=122,
        .x=-4,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=121,[dir_North]=130},
    },
    {.id=123,
        .x=-5,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Forest Dead End",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=124},
    },
    {.id=124,
        .x=-6,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=123,[dir_West]=125},
    },
    {.id=125,
        .x=-7,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"Wolves gather at this part of the forest.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=124,[dir_North]=139,[dir_South]=126},
        .table={15,15},
    },
    {.id=126,
        .x=-7,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=127,[dir_West]=162,[dir_North]=125,[dir_South]=143},
    },
    {.id=127,
        .x=-6,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=128,[dir_West]=126,[dir_South]=129},
        .table={9,9},
    },
    {.id=128,
        .x=-5,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=119,[dir_West]=127,[dir_South]=111},
        .table={10},
    },
    {.id=129,
        .x=-6,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Pasture",
        .desc=L"Animals graze in the pasture.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=111,[dir_North]=127,[dir_South]=109},
        .table={10,10,9},
    },
    {.id=130,
        .x=-4,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Dense Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=131,[dir_West]=135,[dir_North]=133,[dir_South]=122},
    },
    {.id=131,
        .x=-3,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=130,[dir_South]=121},
    },
    {.id=132,
        .x=-3,
        .y=-12,
        .region=db_roomregion_forest,
        .name=L"Forest Stall",
        .desc=L"No description",
        .type=db_roomtype_store,
        .exits={[dir_West]=133},
    },
    {.id=133,
        .x=-4,
        .y=-12,
        .region=db_roomregion_forest,
        .name=L"Dense Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=132,[dir_West]=134,[dir_South]=130},
    },
    {.id=134,
        .x=-5,
        .y=-12,
        .region=db_roomregion_forest,
        .name=L"Dense Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=133,[dir_North]=141},
    },
    {.id=135,
        .x=-5,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Dense Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=130,[dir_West]=136},
    },
    {.id=136,
        .x=-6,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Dense Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=135,[dir_West]=139,[dir_North]=137},
    },
    {.id=137,
        .x=-6,
        .y=-12,
        .region=db_roomregion_forest,
        .name=L"Dense Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=138,[dir_North]=140,[dir_South]=136},
    },
    {.id=138,
        .x=-7,
        .y=-12,
        .region=db_roomregion_forest,
        .name=L"Dense Forest Corner",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=137},
    },
    {.id=139,
        .x=-7,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=136,[dir_South]=125},
    },
    {.id=140,
        .x=-6,
        .y=-13,
        .region=db_roomregion_forest,
        .name=L"Deep Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=141,[dir_North]=142,[dir_South]=137},
    },
    {.id=141,
        .x=-5,
        .y=-13,
        .region=db_roomregion_forest,
        .name=L"Deep Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=140,[dir_South]=134},
    },
    {.id=142,
        .x=-6,
        .y=-14,
        .region=db_roomregion_forest,
        .name=L"Forest End",
        .desc=L"This is where the forest meets the rainforest.",
        .type=db_roomtype_plain,
        .exits={[dir_South]=140},
    },
    {.id=143,
        .x=-7,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Forest",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=144,[dir_North]=126,[dir_South]=189},
    },
    {.id=144,
        .x=-8,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Odd Plantation",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=143,[dir_North]=162},
    },
    {.id=145,
        .x=1,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=146,[dir_South]=78},
    },
    {.id=146,
        .x=2,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=145,[dir_South]=147},
    },
    {.id=147,
        .x=2,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=148,[dir_North]=146},
    },
    {.id=148,
        .x=3,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Hilltop",
        .desc=L"This is the highest point of the hill. You look to the northeast, and you see the cliffs rising through the clouds. The clouds were so thick that they blocked out all the sunlight.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=149,[dir_West]=147,[dir_North]=151,[dir_South]=154},
    },
    {.id=149,
        .x=4,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=148,[dir_South]=153},
    },
    {.id=150,
        .x=4,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=152,[dir_West]=151},
    },
    {.id=151,
        .x=3,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=150,[dir_South]=148},
    },
    {.id=152,
        .x=5,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Valley",
        .desc=L"You see mountains.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=150},
    },
    {.id=153,
        .x=4,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=154,[dir_North]=149},
    },
    {.id=154,
        .x=3,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Hill",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=153,[dir_West]=76,[dir_North]=148},
    },
    {.id=155,
        .x=4,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Plain Debris",
        .desc=L"There is debris.",
        .type=db_roomtype_plain,
        .exits={[dir_South]=156},
    },
    {.id=156,
        .x=4,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Wall Collapse",
        .desc=L"It really makes people wonder how big the city once was.",
        .type=db_roomtype_plain,
        .exits={[dir_West]=69,[dir_North]=155},
    },
    {.id=157,
        .x=-4,
        .y=0,
        .region=db_roomregion_forest,
        .name=L"Drawf Trees",
        .desc=L"These trees here are especially short.",
        .type=db_roomtype_plain,
        .exits={[dir_North]=95},
    },
    {.id=158,
        .x=-6,
        .y=-2,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=98,[dir_North]=107},
    },
    {.id=159,
        .x=-7,
        .y=-3,
        .region=db_roomregion_forest,
        .name=L"Craters",
        .desc=L"You are in a crater.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=107,[dir_North]=105},
    },
    {.id=160,
        .x=-6,
        .y=0,
        .region=db_roomregion_forest,
        .name=L"Shrubs",
        .desc=L"The vegetation ends up here.",
        .type=db_roomtype_plain,
        .exits={[dir_East]=97,[dir_North]=161},
    },
    {.id=161,
        .x=-6,
        .y=-1,
        .region=db_roomregion_forest,
        .name=L"Shrubs",
        .desc=L"The shrubs sway in brackish wind.",
        .type=db_roomtype_plain,
        .exits={[dir_South]=160},
        .table={11,12},
    },
    {.id=162,
        .x=-8,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Odd Plantation",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=126,[dir_South]=144},
    },
    {.id=163,
        .x=-9,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Garden Entrance",
        .desc=L"Followers have built this garden to praise their God.",
        .type=db_roomtype_plain,
        .exits={[dir_North]=164},
    },
    {.id=164,
        .x=-9,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=167,[dir_North]=165,[dir_South]=163},
    },
    {.id=165,
        .x=-9,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=166,[dir_South]=164},
    },
    {.id=166,
        .x=-10,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=165,[dir_South]=167},
    },
    {.id=167,
        .x=-10,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=164,[dir_West]=170,[dir_North]=166,[dir_South]=168},
    },
    {.id=168,
        .x=-10,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=169,[dir_North]=167},
    },
    {.id=169,
        .x=-11,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=168,[dir_West]=174,[dir_South]=175},
    },
    {.id=170,
        .x=-11,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=167,[dir_West]=171,[dir_North]=173},
    },
    {.id=171,
        .x=-12,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=170,[dir_West]=177,[dir_North]=172,[dir_South]=174},
    },
    {.id=172,
        .x=-12,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=173,[dir_West]=183,[dir_North]=181,[dir_South]=171},
    },
    {.id=173,
        .x=-11,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=172,[dir_South]=170},
    },
    {.id=174,
        .x=-12,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=169,[dir_North]=171,[dir_South]=176},
    },
    {.id=175,
        .x=-11,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=176,[dir_North]=169},
    },
    {.id=176,
        .x=-12,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=175,[dir_North]=174},
    },
    {.id=177,
        .x=-13,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=171,[dir_West]=178,[dir_South]=180},
    },
    {.id=178,
        .x=-14,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=177,[dir_South]=179},
    },
    {.id=179,
        .x=-14,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=180,[dir_North]=178},
    },
    {.id=180,
        .x=-13,
        .y=-8,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=179,[dir_North]=177},
    },
    {.id=181,
        .x=-12,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=182,[dir_South]=172},
    },
    {.id=182,
        .x=-13,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Garden",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=181,[dir_South]=183},
    },
    {.id=183,
        .x=-13,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Entrance to a Small Temple",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=172,[dir_West]=184,[dir_North]=182},
    },
    {.id=184,
        .x=-14,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Small Temple",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=183,[dir_West]=187,[dir_North]=185},
    },
    {.id=185,
        .x=-14,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Consecration",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=186,[dir_South]=184},
    },
    {.id=186,
        .x=-15,
        .y=-11,
        .region=db_roomregion_forest,
        .name=L"Oracle",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=185,[dir_South]=187},
    },
    {.id=187,
        .x=-15,
        .y=-10,
        .region=db_roomregion_forest,
        .name=L"Small Temple",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=184,[dir_North]=186,[dir_South]=188},
    },
    {.id=188,
        .x=-15,
        .y=-9,
        .region=db_roomregion_forest,
        .name=L"Small Temple's Side Door",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_North]=187},
    },
    {.id=189,
        .x=-7,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Timberland",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=109,[dir_North]=143,[dir_South]=190},
    },
    {.id=190,
        .x=-7,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Timberland",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=191,[dir_North]=189},
    },
    {.id=191,
        .x=-8,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Bandit Hangout",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=190,[dir_West]=194,[dir_North]=192},
    },
    {.id=192,
        .x=-8,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Bandit Hangout",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_West]=193,[dir_South]=191},
    },
    {.id=193,
        .x=-9,
        .y=-7,
        .region=db_roomregion_forest,
        .name=L"Bandit Hangout",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=192,[dir_South]=194},
    },
    {.id=194,
        .x=-9,
        .y=-6,
        .region=db_roomregion_forest,
        .name=L"Bandit Hideout",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=191,[dir_North]=193,[dir_South]=195},
    },
    {.id=195,
        .x=-9,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Bandit Hideout",
        .desc=L"No description",
        .type=db_roomtype_plain,
        .exits={[dir_East]=196,[dir_North]=194},
    },
    {.id=196,
        .x=-8,
        .y=-5,
        .region=db_roomregion_forest,
        .name=L"Bandit Pub",
        .desc=L"No description",
        .type=db_roomtype_store,
        .exits={[dir_West]=195},
    },
};

nat itemdbsize=sizeof(itemdbs)/sizeof(itemdb);
nat enemydbsize=sizeof(enemydbs)/sizeof(enemydb);
nat roomdbsize=sizeof(roomdbs)/sizeof(roomdb);
#endif
